# eBay Car Sales: Data Cleansing Project

***Goal:***

The main goal of this project is to practice cleaning data. A small analysis will be completed at the end of the project.

***Dataset Introduction:***

For this project we will be working with a dataset of used cars from eBay Kleinanzeigen. This is an ad webpage from the German eBay website. The dataset we will be using for analysis can be found [here](https://www.kaggle.com/datasets/sijovm/used-cars-data-from-ebay-kleinanzeigen). For the purposes of this project, Dataquest has altered the data to give us practice cleaning datasets. This means the link  provided has cleaner data than the one imported into this project.

***Data Cleansing Overview:***
1) Convert column titles from camelcase to snakecase
2) Column breakdown and cleansing
3) Exploring the odometer and price columns
4) Exploring the date columns
5) Correcting incorrect registration year data

***Analysis Findings:***

From our analysis we found that the brands: Volkswagen, BMW, Opel, Mercedes Benz, Auid, Ford, and Renault were in the top 4% of sales on eBay. Audi, Mercedes Benze, and BMW were the most expensive vehicles by brand and Renault and Opel were the cheapest. All of the 7 brands had similar mean mileage regardless of their price.

For more details, see the full analysis below.

## Dataset Initiation and Exploration

To start the project off we will import the necessary modules and read the data into our Jupyter Notebook work space.

**Read:**

In [1]:
#import pandas and numpy modules to increase efficency for data cleansing and analysis
import pandas as pd
import numpy as np

In [2]:
#read csv file into project file and assign it to variable "autos"
autos = pd.read_csv('autos.csv', encoding='latin1')

After reading the `'autos.csv'` file into out project file, we need to gain an overview of the data. Two helpful attributes for this task are DataFrame.info() and DataFrame.head().

**Explore:**

`DataFrame.info()` prints a concise summary of the DataFrame, "autos" while `DataFrame.head()` prints the first 5 rows of the dataset by default.

In [3]:
#information about the autos dataset
autos.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateCrawled          50000 non-null  str
 1   name                 50000 non-null  str
 2   seller               50000 non-null  str
 3   offerType            50000 non-null  str
 4   price                50000 non-null  str
 5   abtest               50000 non-null  str
 6   vehicleType          44905 non-null  str
 7   yearOfRegistration   50000 non-null  int64
 8   gearbox              47320 non-null  str
 9   powerPS              50000 non-null  int64
 10  model                47242 non-null  str
 11  odometer             50000 non-null  str
 12  monthOfRegistration  50000 non-null  int64
 13  fuelType             45518 non-null  str
 14  brand                50000 non-null  str
 15  notRepairedDamage    40171 non-null  str
 16  dateCreated          50000 non-null  str
 17  nrOfPictures         50000 non-null  int64
 18  postalCode           50000 non-null  int64
 19  lastSeen             50000 non-null  str
dtypes: int64(5), str(15)
memory usage: 7.6 MB

In [4]:
#first 5 rows of 'autos' dataset
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

**A few observation abouts data cleansing next steps:**
1) Column names contains some uppercase letters. This formatting is known as camelcase. Python's preferred style is snakecase. To improve readability it may be helpful to convert all letters to lowercase and add an underscore ('_') between words.
2) The vehicle 'type', 'gear box', 'model', 'fuel type', and 'not repaired damage' columns all have null values. The 'not repaired damage', 'vehicle type', and 'fuel type' columns have the most null values (ranked greatest to least in the listed order). With this said, no column has more than 20% null values. 
3) Dates may need to be changed to a simpler format for easier analysis.
4) The price column is currently a string and should be converted to an integer with the dollar sign removed.
5) The odometer column is also currently a string and should be converted to an integer with the distance units 'km' removed.

## Data Cleansing

As a reminder, below is an outline of the data cleansing steps we will take for this dataset:
1) Convert column titles from camelcase to snakecase
2) Column breakdown and cleansing
3) Exploring the odometer and price columns
4) Exploring the date columns
5) Correcting incorrect registration year data

### Camelcase to Snakecase

Our first task will be converting the column names from the camelcase format to Python's preferred snakecase format. This includes converting all letters to lowercase and adding underscores between words. For clarity's sake we will also adjust some of the column names to be more descriptive.

In [5]:
#print the column names
print(autos.columns)

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='str')

In [6]:
#dictionary with replacement names
column_names = {
    'dateCrawled': 'date_crawled',
    'name': 'name',
    'seller': 'seller',
    'offerType': 'offer_type',
    'price': 'price',
    'abtest': 'ab_test',
    'vehicleType': 'vehicle_type', 
    'yearOfRegistration': 'registration_year',
    'gearbox': 'gearbox', 
    'powerPS': 'power_ps',
    'model': 'model',
    'odometer': 'odometer',
    'monthOfRegistration': 'registration_month',
    'fuelType': 'fuel_type',
    'brand': 'brand',
    'notRepairedDamage': 'unrepaired_damage',
    'dateCreated': 'ad_created',
    'nrOfPictures': 'num_photos',
    'postalCode': 'postal_code',
    'lastSeen': 'last_seen'
}

#use 'rename' attribute to convert old column titles to new
autos.rename(columns=column_names, inplace=True)

#print the first row to see if column title changes worked
autos.head(1)

,date_crawled,name,seller,offer_type,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_photos,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54

As we can see from our output above all column names have been changed and are much easier to read!

### Column Breakdown and Cleansing

Our next task is to look for:

1) Columns that have mostly one value that are candidates to be dropped
2) Columns that need more investigation
3) Columns that should be converted to numeric data types

To do this we will use the attribute `DataFrame.describe()` to look at descriptive statistics of the objects in each column.

In [7]:
#descriptive statistics about integer and float dtypes
autos.describe()

,registration_year,power_ps,registration_month,num_photos,postal_code
count,50000.000000,50000.000000,50000.000000,50000.0,50000.000000
mean,2005.073280,116.355920,5.723360,0.0,50813.627300
std,105.712813,209.216627,3.711984,0.0,25779.747957
min,1000.000000,0.000000,0.000000,0.0,1067.000000
25%,1999.000000,70.000000,3.000000,0.0,30451.000000
50%,2003.000000,105.000000,6.000000,0.0,49577.000000
75%,2008.000000,150.000000,9.000000,0.0,71540.000000
max,9999.000000,17700.000000,12.000000,0.0,99998.000000

In [8]:
#descriptive statistics about object dtypes
autos.describe(exclude=np.number)

,date_crawled,name,seller,offer_type,price,ab_test,vehicle_type,gearbox,model,odometer,fuel_type,brand,unrepaired_damage,ad_created,last_seen
count,50000,50000,50000,50000,50000,50000,44905,47320,47242,50000,45518,50000,40171,50000,50000
unique,48213,38754,2,2,2357,2,8,2,245,13,7,40,2,76,39481
top,2016-04-04 16:40:33,Ford_Fiesta,privat,Angebot,$0,test,limousine,manuell,golf,"150,000km",benzin,volkswagen,nein,2016-04-03 00:00:00,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,36993,4024,32424,30107,10687,35232,1946,8

**1.** **Columns with mostly one value** include 'num_photos', 'seller', 'offer_type', 'gearbox', 'fuel_type', and 'unrepaired_damage'. 

Drop Columns:
* 'num_photos': every value is 0
* 'seller': 4,999 privat sellers and 1 unique seller
* 'offer_type': 4,999 Angebot offer and 1 uniqe offer

The other three columns are not as closely dominated and may be important to keep for analysis later.

In [9]:
#drop three columns with mostly 1 value
autos = autos.drop('num_photos', axis=1)
autos = autos.drop('seller', axis=1)
autos = autos.drop('offer_type', axis=1)

autos.head(1)

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54

**2.** **Columns that need more investigating are** 'price' and potentially some of the columns with null values like 'unreparied_damage', 'vehicle_type', and 'fuel_type'.

The only column we are going to spend additional time exploring in this section is the 'price' column. We will start by using the `DataFrame.value_counts()` attribute to give us the number of times each price value appears in the dataset, ordered from most common to least.

In [10]:
#investigate 'price' column closer
autos['price'].value_counts()

price
$0          1421
$500         781
$1,500       734
$2,500       643
$1,200       639
            ...
$145,000       1
$130,000       1
$385           1
$22,200        1
$16,995        1
Name: count, Length: 2357, dtype: int64

Interestingly the most common price is 0 USD with 1,421 occurances. Let's see what happens when we look at only the rows who's column has a price of 0 USD.

In [11]:
#create a copy of the dataset to analyze only the columns where the price is '$0'
autos_copy = autos.copy()
zero_values = autos_copy[autos_copy['price'] == '$0']
zero_values.head()

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
71,2016-03-28 19:39:35,Suche_Opel_Astra_F__Corsa_oder_Kadett_E_mit_Re...,$0,control,NaN,1990,manuell,0,NaN,"5,000km",0,benzin,opel,NaN,2016-03-28 00:00:00,4552,2016-04-07 01:45:48
80,2016-03-09 15:57:57,Nissan_Primera_Hatchback_1_6_16v_73_Kw___99Ps_...,$0,control,coupe,1999,manuell,99,primera,"150,000km",3,benzin,nissan,ja,2016-03-09 00:00:00,66903,2016-03-09 16:43:50
87,2016-03-29 23:37:22,Bmw_520_e39_zum_ausschlachten,$0,control,NaN,2000,NaN,0,5er,"150,000km",0,NaN,bmw,NaN,2016-03-29 00:00:00,82256,2016-04-06 21:18:15
99,2016-04-05 09:48:54,Peugeot_207_CC___Cabrio_Bj_2011,$0,control,cabrio,2011,manuell,0,2_reihe,"60,000km",7,diesel,peugeot,nein,2016-04-05 00:00:00,99735,2016-04-07 12:17:34

In [12]:
#descriptive statistics about the rows with '$0' as the 'price'
zero_values.describe(exclude=np.number)

,date_crawled,name,price,ab_test,vehicle_type,gearbox,model,odometer,fuel_type,brand,unrepaired_damage,ad_created,last_seen
count,1421,1421,1421,1421,915,1088,1126,1421,974,1421,699,1421,1421
unique,1414,1383,1,2,8,2,148,13,5,38,2,37,1405
top,2016-03-19 10:50:25,Opel_Corsa_B,$0,test,limousine,manuell,golf,"150,000km",benzin,volkswagen,nein,2016-03-26 00:00:00,2016-04-06 07:46:43
freq,2,4,1421,731,256,883,124,1002,732,348,450,61,2

Nothing is jumping out after further analysis of the price column. The only exception to that is the 1,421 occurances of $0 values.

**3.** **Columns that should be converted to numeric dtypes are** 'price' and 'odometer'. These columns contain numeric values that are currently string dtypes but should be integer dtypes. We will first remove any non-numeric characters and then convert the data types to integers so future calculations are possible.

In [13]:
#remove non-numeric characters
autos['price'] = autos['price'].str.replace('$', '')
autos['price'] = autos['price'].str.replace(',', '')

autos['odometer'] = autos['odometer'].str.replace('km', '')
autos['odometer'] = autos['odometer'].str.replace(',', '')

#dtype of 'price' and 'odometer' columns
print(f'price data type: {autos['price'].dtype}')
print(f'odometer data type: {autos['odometer'].dtype}')

price data type: str
odometer data type: str

In [14]:
#convert string dtype to numeric
autos['price'] = autos['price'].astype(int)

autos['odometer'] = autos['odometer'].astype(int)

print(f'price dtype: {autos['price'].dtype}')
print(f'odometer dtype: {autos['odometer'].dtype}')

price dtype: int64
odometer dtype: int64

In [15]:
#rename 'odometer' column
autos.rename({'odometer': 'odometer_km'}, axis=1, inplace=True)

od_describe = autos['odometer_km'].describe()
od_describe

count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

### Exploring the Odometer and Price Columns

Now that we have converted the 'odometer_km' and 'price' columns to numeric data types, let's take a deeper look at their values.

**Price Column:**

In [16]:
#number of unique values in the price column
autos['price'].unique().shape[0]

2357

In [17]:
#statistical description of 'price' column
autos['price'].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

In [18]:
#count the number of times each value occurs
price_count = autos['price'].value_counts()

#sort the values based on price from lowest price to highest price
price_count_order = price_count.sort_index(ascending=True)


print(f'Highest Price Occurance: {price_count_order.head(20)}')
print('\n')
print(f'Lowest Price Occurance: {price_count_order.tail(20)}')

Highest Price Occurance: price
0     1421
1      156
2        3
3        1
5        2
8        1
9        1
10       7
11       2
12       3
13       2
14       1
15       2
17       3
18       1
20       4
25       5
29       1
30       7
35       1
Name: count, dtype: int64


Lowest Price Occurance: price
197000      1
198000      1
220000      1
250000      1
259000      1
265000      1
295000      1
299000      1
345000      1
350000      1
999990      1
999999      2
1234566     1
1300000     1
3890000     1
10000000    1
11111111    2
12345678    3
27322222    1
99999999    1
Name: count, dtype: int64

As seen in the previous exploration of the 'price' column, 0 USD occurs 1,421 times. This is unusual given the data is of sales. Another interesting observation is the extremely large price values at the tail of the sorted list. Values appear to jump substantially downward from 99,999,999 until they reach 350,000 USD.

In [19]:
#remove outliers and keep values bewteen 1 and 350,000
autos_filtered = autos[autos['price'].between(1, 350000)]

#sort values based on price from lowest price to highest price
new_sort = autos_filtered['price'].value_counts().sort_index(ascending=True)

print(f'Highest Price Occurance: {new_sort.head()}')
print('\n')
print(f'Lowest Price Occurance: {new_sort.tail()}')

Highest Price Occurance: price
1    156
2      3
3      1
5      2
8      1
Name: count, dtype: int64


Lowest Price Occurance: price
265000    1
295000    1
299000    1
345000    1
350000    1
Name: count, dtype: int64

As we can see from the output above, we have succesfully removed outlier data from the autos dataset. Let's look at the new unique number of values and descriptive statistics.

In [20]:
#number of rows in 'price' column
autos_filtered['price'].unique().shape[0]

2346

In our origional dataset we had 2,357 unique prices. Now we have 11 less unique values: 2,346.

In [21]:
#descriptive statistics of 'price' column
autos_filtered['price'].describe()

count     48565.000000
mean       5888.935591
std        9059.854754
min           1.000000
25%        1200.000000
50%        3000.000000
75%        7490.000000
max      350000.000000
Name: price, dtype: float64

The mean has lowered from 9,840 to 5,888 and the standard deviation has decreased from 480,000 to 9,059 which mean there less variance in the distribution of our data or few outliers. Most other values remain the same.

**Odometer Column:**

Similarly to the 'price' column, we will review the number of rows, descriptive statistics, and the number of occurances of each value in the 'odometer' column.

In [22]:
#number of unique values in the 'odometer_km' column
autos_filtered['odometer_km'].unique().shape[0]

13

In [23]:
#statistical description of 'odometer_km' column
autos_filtered['odometer_km'].describe()

count     48565.000000
mean     125770.101925
std       39788.636804
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [24]:
#count the number of times each value occurs
od_count = autos_filtered['odometer_km'].value_counts()

#sort the values based on the frequency they occur from highest occurance to lowest occurance
od_count_order = od_count.sort_index(ascending=False)


print(f'Highest to Lowest Odometer Occurance: {od_count_order}')

Highest to Lowest Odometer Occurance: odometer_km
150000    31414
125000     5057
100000     2115
90000      1734
80000      1415
70000      1217
60000      1155
50000      1012
40000       815
30000       780
20000       762
10000       253
5000        836
Name: count, dtype: int64

The 'odometer_km' column does not have any outstanding values that need to be removed so we will leave this one alone.

### Exploring the Date Columns

There are five columns with date values: 'date_crawled', 'ad_created', 'last_seen', 'registration_year', and 'registration_month'. The first three of these date values are string dtypes while the last two are numeric dtypes. Instead of converting the string date values to numeric dtypes we will prune the length and then run a basic statistical analysis against that. Below are the string date values in their full form.

In [25]:
#explore date columns 
autos_filtered[['date_crawled','ad_created','last_seen']][0:5]

          date_crawled           ad_created            last_seen
0  2016-03-26 17:47:46  2016-03-26 00:00:00  2016-04-06 06:45:54
1  2016-04-04 13:38:56  2016-04-04 00:00:00  2016-04-06 14:45:08
2  2016-03-26 18:57:24  2016-03-26 00:00:00  2016-04-06 20:15:37
3  2016-03-12 16:58:10  2016-03-12 00:00:00  2016-03-15 03:16:28
4  2016-04-01 14:38:50  2016-04-01 00:00:00  2016-04-01 14:38:50

As you can see the date values also have timestamps. The timestamps are not important for our analysis so we will remove those and just use the year/month/date format for our analysis. 

For 'date_crawled', 'ad_created', and 'last_seen' we will...
1) Extract the first ten character of the string
2) Count the number of times each date appears in the dataset
3) Sort based on the date with the most recent date being at the top and the furthest date being at the bottom

**date_crawled:**

In [26]:
#extract first 10 character from date column
autos_filtered['date_crawled'].str[:10]

0        2016-03-26
1        2016-04-04
2        2016-03-26
3        2016-03-12
4        2016-04-01
            ...
49995    2016-03-27
49996    2016-03-28
49997    2016-04-02
49998    2016-03-08
49999    2016-03-14
Name: date_crawled, Length: 48565, dtype: str

In [27]:
#using first 10 characters count the number of occurances per value
percent_dc = autos_filtered['date_crawled'].str[:10].value_counts(normalize=True, dropna=False)

#order by date from nearest date to farthest date
sort_dc = percent_dc.sort_index(ascending=False)

print(sort_dc.head())
print('\n')
print(sort_dc.tail())
print('\n')
print(len(sort_dc))

date_crawled
2016-04-07    0.001400
2016-04-06    0.003171
2016-04-05    0.013096
2016-04-04    0.036487
2016-04-03    0.038608
Name: proportion, dtype: float64


date_crawled
2016-03-09    0.033090
2016-03-08    0.033296
2016-03-07    0.036014
2016-03-06    0.014043
2016-03-05    0.025327
Name: proportion, dtype: float64


34

The earliest date is 2016-03-05 and the latest date it 2016-04-07. There are 34 unique values in this column.

In [28]:
sort_dc.describe()

count    34.000000
mean      0.029412
std       0.009762
min       0.001400
25%       0.029980
50%       0.032781
75%       0.034840
max       0.038608
Name: proportion, dtype: float64

It appears that most of the date values make up about 3% of the 'date_crawled' data: a very even distribution.

**ad_created:**

In [29]:
#using first 10 characters count the number of occurances per value
percent_ac = autos_filtered['ad_created'].str[:10].value_counts(normalize=True, dropna=False)

#order by date from nearest date to farthest date
sort_ac = percent_ac.sort_index(ascending=False)

print(sort_ac.head())
print('\n')
print(sort_ac.tail())
print('\n')
print(len(sort_ac))

ad_created
2016-04-07    0.001256
2016-04-06    0.003253
2016-04-05    0.011819
2016-04-04    0.036858
2016-04-03    0.038855
Name: proportion, dtype: float64


ad_created
2015-12-05    0.000021
2015-11-10    0.000021
2015-09-09    0.000021
2015-08-10    0.000021
2015-06-11    0.000021
Name: proportion, dtype: float64


76

The earliest date is 2015-06-11 and the latest date is 2016-04-07. A larger distribution with 76 unique values in this column.

In [30]:
sort_ac.describe()

count    76.000000
mean      0.013158
std       0.015956
min       0.000021
25%       0.000021
50%       0.000144
75%       0.032112
max       0.038855
Name: proportion, dtype: float64

The distribution is larger here with 50% of the date values making up less than 1% of the 'ad_created' column.

**last_seen:**

In [31]:
#using first 10 characters count the number of occurances per value
percent_ls = autos_filtered['last_seen'].str[:10].value_counts(normalize=True, dropna=False)

#order by date from nearest date to farthest date
sort_ls = percent_ls.sort_index(ascending=False)

print(sort_ls.head())
print('\n')
print(sort_ls.tail())
print('\n')
print(len(sort_ls))

last_seen
2016-04-07    0.131947
2016-04-06    0.221806
2016-04-05    0.124761
2016-04-04    0.024483
2016-04-03    0.025203
Name: proportion, dtype: float64


last_seen
2016-03-09    0.009595
2016-03-08    0.007413
2016-03-07    0.005395
2016-03-06    0.004324
2016-03-05    0.001071
Name: proportion, dtype: float64


34

The earliest date is 2016-03-05 and the latest date is 2016-04-07. There are 34 unique values in this column.

In [32]:
sort_ls.describe()

count    34.000000
mean      0.029412
std       0.043718
min       0.001071
25%       0.012432
50%       0.019489
75%       0.023783
max       0.221806
Name: proportion, dtype: float64

A much larger deviation in the percentile date values here with a standard deviation of about 4%. From the statistics 50% of the date values appear to make up around 2% or less of the entire column values.

**registration_year:**

'registration_year' is the last date column we will analyze. Since this columns has date values in a numeric dtype we can easily apply the `.describe()` attribute to the column to gain our descriptive statistics.

In [33]:
#descriptive statistics about the 'registration_year'
autos_filtered['registration_year'].describe()

count    48565.000000
mean      2004.755421
std         88.643887
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

The standard deviation here is very large at 88%. If we look closely we will notice the minimum value in this column is 1000 and the largest value is 9999. This definitely is an error since 1000 is before cars were invented and 9999 is way into the future. We will need to take a closer look into these values.

### Incorrect Registration Year Data

As we established, some of the date values in our 'registration_year' column are inaccurate. We automatically know that values can't exceed the year 2016 since a car can't be registed before the car was seen. To start our analysis we will look at the number of values outside of the range 1900-2016 and see what returns.

In [34]:
#create a copy of the dataset for analysis
autos_filt_copy = autos_filtered.copy()

#look at the values above 2016 and below 1900
outliers = autos_filt_copy[(autos_filt_copy['registration_year'] < 1900) | (autos_filt_copy['registration_year'] > 2016)]

outliers['registration_year']

10       2017
55       2017
65       2017
68       2017
84       2018
         ...
49770    2018
49796    2017
49841    2017
49910    9000
49935    2017
Name: registration_year, Length: 1884, dtype: int64

In [35]:
#number of times each year appears
outliers['registration_year'].value_counts()

registration_year
2017    1392
2018     470
5000       4
9999       3
2019       2
1800       2
4500       1
4100       1
6200       1
1000       1
1111       1
8888       1
2800       1
5911       1
4800       1
1001       1
9000       1
Name: count, dtype: int64

It looks like most of the incorrect dates are registered for 2017 and 2018. Nonetheless, these values cannot reasonable be correct since the dataset was collected in 2016. Our next task will be to remove values below 1900 and above 2016.

In [36]:
#use the origional dataset to keep only the entries between 1900 and 2016
autos_filt = autos_filtered[(autos_filtered['registration_year'].between(1900, 2016))]

#count the number of times each value is in the dataset and sort based on year from closer to farther
sort_ry = autos_filt['registration_year'].value_counts(normalize=True).sort_index(ascending=False)

sort_ry

registration_year
2016    0.026135
2015    0.008397
2014    0.014203
2013    0.017202
2012    0.028063
          ...
1934    0.000043
1931    0.000021
1929    0.000021
1927    0.000021
1910    0.000107
Name: proportion, Length: 78, dtype: float64

In [37]:
#descriptive statistics on sort_ry
sort_ry.describe()

count    78.000000
mean      0.012821
std       0.020679
min       0.000021
25%       0.000091
50%       0.000718
75%       0.016452
max       0.067608
Name: proportion, dtype: float64

We now have a much smaller standard deviation of about 2%.

### Data Cleansing Conclusion

We have offically completed our data cleansing steps for this project. As an overview here are the things we completed:

1) Convert column titles from camelcase to snakecase
2) Column breakdown and cleansing
3) Exploring the odometer and price columns
4) Exploring the date columns
5) Correcting incorrect registration year data

## Dataset Analysis

The final part this this project is a small exploration of the mean price of top brands sold on eBay.

### Exploring Price by Brand

As stated above our analysis will consist of exploring the mean price of top car brands sold on eBay. To start we will count the number of times each brand appears in the dataset and then find the mean price of the top brands.

In [38]:
#count the number of times each brand appears (value_counts automatically sorts highest to lowest)
brand_sort = autos_filt['brand'].value_counts(normalize=True)

brand_sort.head(20)

brand
volkswagen        0.211264
bmw               0.110045
opel              0.107581
mercedes_benz     0.096463
audi              0.086566
ford              0.069900
renault           0.047150
peugeot           0.029841
fiat              0.025642
seat              0.018273
skoda             0.016409
nissan            0.015274
mazda             0.015188
smart             0.014160
citroen           0.014010
toyota            0.012703
hyundai           0.010025
sonstige_autos    0.009811
volvo             0.009147
mini              0.008762
Name: proportion, dtype: float64

We will use the top 4% of brands for our analysis since the percent makeup of brands under the 4% marker are closer in distribution. That leaves 7 vehicles for our analysis: Volkswagen, BMW, Opel, Mercedes Benz, Auid, Ford, and Renault.

Our next task is to seperate the top 4% for our analysis.

In [39]:
#from the brand column select only those that make up 4% or more of the sales by brand
top_4_perc = brand_sort[brand_sort >= 0.04].index

top_4_perc

Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford',
       'renault'],
      dtype='str', name='brand')

Finally, we will calculate the mean price of the top 4% and order based on cost (most expensive at the top).

In [40]:
#create a dictionary that holds the car brand and mean price
mean_brand_price = {}

for brand in top_4_perc:
    key = autos_filt[autos_filt['brand'] == brand]
    mean_brand_price[brand] = int(key['price'].mean())

#sort dictionary by converting key-value-pairs to tuples and order given index 1 of tuple - descending
dic_sorted = sorted(mean_brand_price.items(), key=lambda x: x[1], reverse=True)

dic_sorted

[('audi', 9336),
 ('mercedes_benz', 8628),
 ('bmw', 8332),
 ('volkswagen', 5402),
 ('ford', 3749),
 ('opel', 2975),
 ('renault', 2474)]

On average the most expensive vehicles are from Audi and the cheapest are from Renault. The top 4% of cars sold on eBay have a wide price range.

### Storing Aggregate Data in a DataFrame

Our last task will be to store our mean price by brand data in a DataFrame so we can look at other aggregate data side-by-side. The process is simply to convert the dictionary into a Series using the `.Series()` attribute and then making it a two-dimensional DataFrame using the `.DataFrame()` attribute.

In [41]:
#convert dictionary to pandas Series
brand_price_series = pd.Series(mean_brand_price)
brand_price_series

volkswagen       5402
bmw              8332
opel             2975
mercedes_benz    8628
audi             9336
ford             3749
renault          2474
dtype: int64

In [42]:
#create a DataFrame from pandas Series
brand_price_df = pd.DataFrame(brand_price_series, columns=['mean_price'])
brand_price_df

               mean_price
volkswagen           5402
bmw                  8332
opel                 2975
mercedes_benz        8628
audi                 9336
ford                 3749
renault              2474

To demonstrate the benefit of holding aggregate data in a DataFrame, we will quickly calculate the mean mileage of the top 4% of vehicle by brand. We will then turn the dictionary into a Series and add it to out 'brand_price_df' DataFrame so we can view the aggregated data side-by-side.

In [43]:
#create a dictionary that holds the car brand and mean mileage
mean_brand_mileage = {}

for brand in top_4_perc:
    key = autos_filt[autos_filt['brand'] == brand]
    mean_brand_mileage[brand] = int(key['odometer_km'].mean())

#sort dictionary by converting key-value-pairs to tuples and order given index 1 of tuple - descending
dic = sorted(mean_brand_mileage.items(), key=lambda x: x[1], reverse=True)

dic

[('bmw', 132572),
 ('mercedes_benz', 130788),
 ('opel', 129310),
 ('audi', 129157),
 ('volkswagen', 128707),
 ('renault', 128071),
 ('ford', 124266)]

In [44]:
#convert dictionary to pandas Series
brand_mileage = pd.Series(mean_brand_mileage)
brand_mileage

volkswagen       128707
bmw              132572
opel             129310
mercedes_benz    130788
audi             129157
ford             124266
renault          128071
dtype: int64

In [45]:
#assign the new 'brand_mileage' Series to our existing 'brand_price_df' DataFrame
brand_price_df['brand_mileage'] = brand_mileage

#rename 'brand_mileage' to 'mean_mileage'
brand_price_df.rename({'brand_mileage': 'mean_mileage'}, axis=1, inplace=True)
brand_price_df

               mean_price  mean_mileage
volkswagen           5402        128707
bmw                  8332        132572
opel                 2975        129310
mercedes_benz        8628        130788
audi                 9336        129157
ford                 3749        124266
renault              2474        128071

Now we can see our 'mean_price' and 'mean_mileage' by brand side-by-side. We could use this to preform basic statistical analysis between columns or within columns. Given the output, it appears that most cars, independent of brand and price, have a similar mean mileage between 120,000km and 135,000km.

### Data Analysis Conclusion

From our analysis we found that the brands: Volkswagen, BMW, Opel, Mercedes Benz, Auid, Ford, and Renault were in the top 4% of sales on eBay. Audi, Mercedes Benze, and BMW were the most expensive vehicles by brand and Renault and Opel were the cheapest. All of the 7 brands had similar mean mileage regardless of their price.